$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
# Suggestions can sometimes take longer on CI machines,
# leading to inconsistent results.
suggestionsTimeout: 5000 # ms
dictionaryDefinitions:
  - name: project-words
    path: ../../project-words.txt
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - node_modules
  - /project-words.txt
